sample_app/urls.py
app_name = "sample_app"
from django.urls import path
from . import views

urlpatterns = [
    # Task
    path('', views.home, name="home"), # if no URL is provided, go to task list page
    path('task/all/', views.task_list, name="task_list"), # URL to view all tasks (task list page)
    path('task/', views.task_details, name="task_details"), # URL to view task details for a given task ID
    path('task/new/', views.create_task, name="create_task"), # URL for create task page
    path('task/<int:task_id>/update/<str:update>/<str:auth_token>/', views.update_task, name="update_task"), # URL to update task status to Closed or to set it again to Open
    # Task Responses
    path('response/', views.response_details, name="response_details"), # URL to view response details for a given response ID and task ID
    path('response/new/', views.create_response, name="create_response"), # URL for create response page for a given task ID
    path('response/<int:response_id>/judge/<int:judgement>/<str:auth_token>/', views.judge_response, name="judge_response") # URL to approve/reject responses
]

# URLS to register with QuriOSINTy:
# Home Page: BASE_URL + "/"
# Task Details: BASE_URL + "/task/"
# New Task: BASE_URL + "/task/new/"
# Response Details: BASE_URL + "/response/"
# New Response: BASE_URL + "/response/new/"

verification_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sample_app.urls')), # this includes your sample app urls in your main project
]

sample_app/models.py
from django.db import models

# Create your models here.

sample_app/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponse, HttpResponseRedirect
import json
import requests
import datetime
from dateutil.parser import parse

# Set the base URL here:
API_BASE_URL = "https://quriosinty.herokuapp.com/api/v1/"
# API_BASE_URL = "http://localhost:8080/api/v1/"
# Create your views here.

# VIEWS FOR TASKS
def home(request):
    return render(request, 'home.html')

def create_task(request):
    if request.method == 'GET':
        task = {}
        context = {'page_type': 'task',
                'task': task}
        return render(request, 'create_task.html', context)

    elif request.method == 'POST':
        post = request.POST
        # get it from the POST request
        auth_token = str(post['token'].strip())
        tool_id = int(post['tool'].strip())
        event_id = int(post['event'].strip()) 

        data = {"img_url":post['img_url'].strip(), "q1":post['q1'].strip(), "q2":post['q2'].strip(), "q3":post['q3'].strip()}

        # create the request object with data from the POST request
        request = { 
                    "tool": tool_id,
                    "event_id": event_id,
                    "name": post['task_name'].strip(),
                    "status": "Open",
                    "description": post['task_description'].strip(),
                    "time_estimate": post['time_estimate'].strip(),
                    "data": data,
                    "request_responses": int(post['num_responses'].strip())
                }
        print("DATA REQUEST", json.dumps(request))

        # sending post request and saving the response as response object
        url = API_BASE_URL + "task/" # URL for API call
        data = json.dumps(request) # convert dictionary to JSON
    
        headers = {'content-type': 'application/json', 'Authorization': 'Token {}'.format(auth_token)}  # header type and authorization
        response = requests.post(url = url, data = data, headers = headers) # make the post request
        data = response.json() # extracting response data in json format
        print("DATA RESPONSE Create Task", data, response)

        content = {
            "task": data["id"],
            "event": event_id,
            "token": auth_token,
            "tool": tool_id
        }
        return HttpResponse(status=200,content=json.dumps(content))
    
    else:
        return HttpResponse(status=400)

def update_task(request, task_id, update, auth_token):
    print("UPDATING TASK")
    patch = {} # create the patch object
    if update == "closed":
        patch = {"status": "Closed"} # set to Closed
    elif update == "open":
        patch = {"status": "Open"} # set to Opened
    else :
        return HttpResponse(status=400) # error

    # NOTE API CALL SETUP: call task GET API to update status of a task as closed
    url = API_BASE_URL + "task/"+str(task_id)+"/" # URL for API call
    
    data = json.dumps(patch) # convert dictionary to JSON

    headers = {'content-type': 'application/json', 'Authorization': 'Token {}'.format(auth_token)}  # header type and authorization
    response = requests.patch(url = url, data = data, headers = headers) # make the patch request [PATCH is for partial updates; while PUT updates all required fields; POST is for creating new objects]
    data = response.json() # extracting response data in json format
    print("DATA RESPONSE", data)

    if response.status_code == 200: # if updating the task as closed was succesful
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=400)

def task_list(request):
    # NOTE API CALL SETUP: call task GET API to get all tasks
    url = API_BASE_URL + "task/" # URL for API call
    response = requests.get(url = url) # make the get request
    data = response.json() # extracting response data in json format
    print("DATA RESPONSE TASK LIST", data)

    # parse the response
    tasks = []
    for task in data:
        if task["tool_name"] == "Photo Verification Sample App" : 
            # NOTE API CALL SETUP: call task GET API to get all responses for a given task 
            # NOTE This is an inefficient way to do it, we are working on an API call that just returns a) total number of responses and b) number of completed responses
            url = API_BASE_URL + "task/"+str(task['id'])+"/response" # URL for API call
            response = requests.get(url = url) # make the get request
            data = response.json() # extracting response data in json format
            print("DATA RESPONSE Task_Response", data)
            num_completed = len(data)

            data = task['data']
            temp_task = {
                "id": task['id'],
                "name": task['name'],
                "status": task['status'],
                "description": task['description'],
                "date_created": task['date_created'],
                "img_url": data['img_url'],
                "q1": data['q1'],
                "q2": data['q2'],
                "q3": data['q3'],
                "num_responses": task['request_responses'],
                "num_completed": num_completed
            }
            tasks.append(temp_task)

    context = {'page_type': 'task',
               'tasks': tasks}
    return render(request, 'tasks.html', context)

def task_details(request):
    # NOTE API CALL SETUP: call task GET API to get all responses for a given task 
    # NOTE This is an inefficient way to do it, we are working on an API call that just returns a) total number of responses and b) number of completed responses
    task_id = request.GET["task"]
    url = API_BASE_URL + "task/"+str(task_id)+"/response" # URL for API call
    response = requests.get(url = url) # make the get request
    data = response.json() # extracting response data in json format
    print("DATA RESPONSE Task_Response", data)
    num_completed = len(data)

    # NOTE API CALL SETUP: call task GET API to get one task
    url = API_BASE_URL + "task/"+str(task_id)+"/" # URL for API call
    response = requests.get(url = url) # make the get request
    data = response.json() # extracting response data in json format
    print("DATA RESPONSE Task", data)
    t_data = data['data']
    requested_responses = data['request_responses']

    task = {
            "id": data['id'],
            "name": data['name'],
            "status": data['status'],
            "description": data['description'],
            "date_created": data['date_created'],
            "img_url": t_data['img_url'],
            "q1": t_data['q1'],
            "q2": t_data['q2'],
            "q3": t_data['q3'],
            "num_responses": data['request_responses'],
            "num_completed": num_completed
        }

    # NOTE API CALL SETUP: call task GET API to get all responses for a given task
    url = API_BASE_URL + "task/"+str(task_id)+"/response" # URL for API call
    response = requests.get(url = url) # make the get request
    data = response.json() # extracting response data in json format
    print("DATA RESPONSE Task_Response", data)

    responses = []
    for response in data: 
        ans = response['data']
        temp_response = { 
                    "id": response['id'],
                    "date_created": response['date_created'],
                    "created_by": response['created_by'],
                    "status": response['status'],
                    "ans1": ans['ans1'],
                    "ans2": ans['ans2'],
                    "ans3": ans['ans3'],
                }
        print("TEMP RESPONSE", temp_response)
        responses.append(temp_response)

    responses_allowed = False
    print("NUMBER OF RESPONSES REQUESTED", requested_responses)
    print("NUMBER OF RESPONSES COMPLETED", num_completed)
    if num_completed < requested_responses :
        responses_allowed = True

    context = {'page_type': 'task',
               'token': request.GET["token"],
               'event': request.GET["event"],
               'tool': request.GET["tool"],
               'task': task,
               'responses': responses,
               'responses_allowed': responses_allowed   
            }
    return render(request, 'task_details.html', context)

# VIEWS FOR TASK RESPONSES
def create_response(request):
    if request.method == 'GET':
        # print("REQUEST",request.GET) # this is to view the URL query parameters (e.g., "/?token=<string>&event=<int>&tool=<tool>")
        auth_token = request.GET["token"] # get the authorization token for that user from the URL query string ("token=<string>")
        tool_id = int(request.GET["tool"]) # get the tool ID from the URL query string ("tool=<int>")
        event_id = int(request.GET["event"]) # get the event ID from the URL query string ("event=<int>")
        task_id = int(request.GET["task"]) # get the task ID from the URL query string ("task=<int>")

        # NOTE API CALL SETUP: call task GET API to get all responses for a given task 
        # NOTE This is an inefficient way to do it, we are working on an API call that just returns a) total number of responses and b) number of completed responses
        url = API_BASE_URL + "task/"+str(task_id)+"/response/" # URL for API call
        response = requests.get(url = url) # make the get request
        data = response.json() # extracting response data in json format
        print("DATA RESPONSE Task_Response", data)
        num_completed = len(data)

        # NOTE API CALL SETUP: call task GET API to get one task (to display to the user)
        url = API_BASE_URL + "task/"+str(task_id)+"/"  # URL for API call
        response = requests.get(url = url) # make the get request
        data = response.json() # extracting response data in json format
        print("DATA RESPONSE Task", data)

        t_data = data['data']
        task = {"id": data['id'],
                "name": data['name'],
                "status": data['status'],

sample_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Home</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    {% block scripts %}{% endblock %}
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" crossorigin="anonymous">
    {% block css %}{% endblock %}
    
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Photo Verification App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if page_type == "task" %}
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{%url 'sample_app:task_list' %}">All Tasks</a>
            <!-- <a href="{%url 'sample_app:create_task' %}"><button class="btn btn-outline-success" type="button">New Task</button></a> -->
          </div>
        </div>
      {% endif %}
  </nav>

  <div id="container">
      <div id="content">
          <main>
              {% block page %}
              {% endblock %}
          </main>

      </div>
  </div>

  <!-- JavaScript -->
    <!-- jQuery first then Bootstrap JS, FontAwesome, DataTable -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/64916a7011.js" crossorigin="anonymous"></script>
    <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
</body>
</html>

sample_app/templates/create_response.html
{% extends "base.html" %}
{% load static %}
{% block page %}

<br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
            </div>
            
            <div class="col">

                <form method="POST" id="create_response_form">
                    {% csrf_token %}
                        <h4>
                            Task {{ task.id }}: {{ task.name }}
                        </h4>
                <br>
                <fieldset>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="task_description" class="col-sm-1 font-weight-bold">Description</label>
                        <span>{{ task.description }}</span>
                        <div class="col-sm-1"></div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="img_url" class="col-sm-1 font-weight-bold">Image URL</label>
                        <span>{{ task.img_url }}</span>
                        <div class="col-sm-1"></div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <div class="col">
                            <div class="image-preview" id="imagePreview">
                                <img src="{{ task.img_url }}" alt="" class="image-preview__image" id="previewImage" style="max-width:500px; max-height:500px;">
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                    <hr><hr>
                    {% if task.status == 'Open' and responses_allowed == True %}
                        <h5>Answer the following questions:</h5>
                        <br>
                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <label for="ans1" class="font-weight-bold">Question 1: {{ task.q1 }}</label>
                            <div class="col-6">
                                <input type="text" class="form-control" id="ans1" placeholder="Enter your answer" required>
                            </div>
                            <div class="col-sm-2"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <label for="ans2" class="font-weight-bold">Question 2: {{ task.q2 }}</label>
                            <div class="col-6">
                                <input type="text" class="form-control" id="ans2" placeholder="Enter your answer">
                            </div>
                            <div class="col-sm-2"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <label for="ans3" class="font-weight-bold">Question 3: {{ task.q3 }}</label>
                            <div class="col-6">
                                <input type="text" class="form-control" id="ans3" placeholder="Enter your answer">
                            </div>
                            <div class="col-sm-2"></div>
                        </div>

                        </fieldset>
                        <br>
                        <div class="row">
                            <div class="col"></div>
                            <div class="col">
                                <button id="submit_btn" class="btn btn-primary" type="submit">Submit</button>
                            </div>
                            <div class="col"></div>
                        </div>
                    {% else %}
                        <p>
                            {% if responses_allowed == False %} 
                                No more responses needed.
                            {% endif %}
                            This task is closed. Please contribute to an open task. Thanks!
                        </p>
                    {% endif %}
                </form>
            </div>

            <div class="col-2">
            </div>
    </div>

    <script src="{% static 'js/create_response.js' %}"></script>
{% endblock page %}

sample_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block page %}

<p>
    This is the home page for Photo Verification App.
    You can find more instructions on how to use this tool on this page.
</p>

{% endblock page %}

sample_app/templates/response_details.html
{% extends "base.html" %}
{% load static %}
{% block page %}

<br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
            </div>
            
            <div class="col">
                <h3>
                    <a href="">Task {{ task.id }}</a>: {{ task.name }}
                </h3>
                <h5>Task Status: {{ task.status }} </h5> 
                <h5>Date Created: {{ task.date_created }} </h5>
                <h5>Created By: {{ task.created_by }} </h5>
                <!-- <button class="btn btn-danger">Close Task</button> -->
                <fieldset>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="img_url" class="col-sm-1 col-form-label font-weight-bold">Image URL</label>
                        <span>{{ task.img_url }}</span>
                        <div class="col-sm-1"></div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <div class="col">
                            <div class="image-preview" id="imagePreview">
                                <img src="{{ task.img_url }}" alt="" class="image-preview__image" id="previewImage" style="max-width:500px; max-height:500px;">
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                <hr><hr>    
                <h3>
                    Response {{ response.id }}
                </h3>
                <h5>Response Status: {{ response.status }} </h5>
                <h5>Created By: {{ response.created_by }} </h5>
                <h5>Date created: {{ response.date_created }} </h5>
                <br>
                <fieldset>                 
                    <h5>Responses to the 3 questions:</h5>
                    <br>
                    <div class="form-group">
                        <div class="col-sm-1"></div>
                        <label for="q1" class="col font-weight-bold"><h5>Question 1: {{ task.q1 }}</h5></label>
                        <h5><span class="font-weight-bold">Answer: </span><span>{{ response.ans1 }}</span></h5>
                        <div class="col-sm-1"></div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1"></div>
                        <label for="q2" class="col font-weight-bold"><h5>Question 2: {{ task.q2 }}</h5></label>
                        <h5><span class="font-weight-bold">Answer: </span><span>{{ response.ans2 }}</span></h5>
                        <div class="col-sm-1"></div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-1"></div>
                        <label for="q3" class="col font-weight-bold"><h5>Question 3: {{ task.q3 }}</h5></label>
                        <h5><span class="font-weight-bold">Answer: </span><span>{{ response.ans3 }}</span></h5>
                        <div class="col-sm-1"></div>
                    </div>
                    
                </fieldset>
                <br>

                    {% if is_task_owner == "True" %}
                        <div class="row">
                            <div class="col"></div>
                            <div class="col">
                                {% if response.status == "Pending" or response.status == "Rejected" %}<button id="approve_response_btn" class="btn btn-success" type="button">Approve Response</button>{% endif %}
                                {% if response.status == "Pending" or response.status == "Approved" %}<button id="reject_response_btn" class="btn btn-danger" type="button">Reject Response</button>{% endif %}
                            </div>
                            <div class="col"></div>
                        </div>
                    {% endif %}
                
            </div>

            <div class="col-2">
            </div>
    </div>
    <br><br>
    <script src="{% static 'js/response_details.js' %}"></script>
{% endblock page %}

sample_app/templates/task_details.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
{% block page %}

<br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
            </div>
            
            <div class="col">
                <h3>
                    Task {{ task.id }}: {{ task.name }}
                </h3>
                <h5>Status: {{ task.status }}</h5> 
                <h5>Date Created: {{ task.date_created }}</h5>
                {% if task.status == "Open" %}<button id="close_task_btn" class="btn btn-danger">Close Task</button>{% endif %}
                {% if task.status == "Closed" %}<button id="reopen_task_btn" class="btn btn-success">Reopen Task</button>{% endif %}
                <fieldset>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="img_url" class="col-sm-1 font-weight-bold">Image URL</label>
                        <span>{{ task.img_url }}</span>
                        <div class="col-sm-1"></div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <div class="col">
                            <div class="image-preview" id="imagePreview">
                                <img src="{{ task.img_url }}" alt="" class="image-preview__image" id="previewImage" style="max-width:300px; max-height:300px;">
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                    </div>
                    
                    
                    <h5>Your 3 questions:</h5>
                    <br>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="q1" class="col-sm-1 font-weight-bold">Question 1</label>
                        <span>{{ task.q1 }}</span>
                        <div class="col-sm-1"></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="q2" class="col-sm-1 font-weight-bold">Question 2</label>
                        <span>{{ task.q2 }}</span>
                        <div class="col-sm-1"></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="q3" class="col-sm-1 font-weight-bold">Question 3</label>
                        <span>{{ task.q3 }}</span>
                        <div class="col-sm-1"></div>
                    </div>

                    <br>
                    <h4>Task Responses:</h4>
                    <br>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <div class="col-sm-6">
                            {% if task.status == "Closed" %}<span>Note: Your task is closed.</span>{% endif %}
                            {% if responses_allowed == False %}<span>Note: All requested responses have been submitted.</span>{% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="num_responses" class="col-sm-2 font-weight-bold">Requested Responses</label>
                        <div class="col">
                            <span class="">{{ task.num_responses }}</span>
                            </select>
                        </div>
                        <div class="col-sm-6"></div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-1"></div>
                        <label for="num_responses" class="col-sm-2 font-weight-bold">Completed Responses</label>
                        <div class="col">
                            <span class="">{{ task.num_completed }}</span>
                        </div>
                        <div class="col-sm-6"></div>
                    </div>

                    <div class="table-width">
                        <table class="task-response-table" id="task_response_table">
                            <thead>
                            <tr>
                                <th scope="col">Response ID</th>
                                <th scope="col">Response - Q1</th>
                                <th scope="col">Response - Q2</th>
                                <th scope="col">Response - Q3</th>
                                <th scope="col">Created By</th>
                                <th scope="col">Date Created</th>
                                <th scope="col">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for response in responses %}
                                <tr>
                                    <td scope="row">{{ response.id }} <a href="{% url 'sample_app:response_details' %}?token={{ token }}&event={{ event }}&task={{ task.id }}&response={{ response.id }}&tool={{ tool }}"><i class="primary fas fa-external-link-alt"></i></a></td>
                                    <td>{{ response.ans1 }}</td>
                                    <td>{{ response.ans2 }}</td>
                                    <td>{{ response.ans3 }}</td>
                                    <td>{{ response.created_by }}</td>
                                    <td>{{ response.date_created }}</td>
                                    <td>{{ response.status }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    
                </fieldset>
                <br>
            </div>

            <div class="col-2">
            </div>
    </div>

    <script src="{% static 'js/task_details.js' %}"></script>
{% endblock page %}

sample_app/templates/tasks.html
{% extends "base.html" %}
{% load static %}
{% block page %}

<br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
            </div>
            
            <div class="col">
                <h3>
                    All My Tasks
                </h3>
                <fieldset>
                    <div class="table-width">
                        <table class="task-response-table" id="task_response_table">
                            <thead>
                            <tr>
                                <th scope="col">Task ID</th>
                                <th scope="col">Task Name</th>
                                <th scope="col">Description</th>
                                <th scope="col">Completed Responses</th>
                                <th scope="col">Requested Responses</th>
                                <th scope="col">Date Created</th>
                                <th scope="col">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for task in tasks %}
                                <tr>
                                    <td>{{ task.id }}</td>
                                    <td>{{ task.name }} <a href="{% url 'sample_app:task_details' task.id %}"><i class="fas fa-external-link-alt"></i></a></td>
                                    <td>{{ task.description }}</td>
                                    <td>{{ task.num_completed }}</td>
                                    <td>{{ task.num_responses }}</td>
                                    <td>{{ task.date_created }}</td>
                                    <td>{{ task.status }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    
                </fieldset>
                    <br>
            </div>

            <div class="col-2">
            </div>
    </div>

    <script src="{% static 'js/task_details.js' %}"></script>
{% endblock page %}